import fs from 'fs';
import path from 'path';
import prompts from 'prompts';

const MODELS = [
  { title: 'Claude Sonnet 4 (recommended)', value: 'claude-sonnet-4-20250514' },
  { title: 'Claude Opus 4 (most capable)',  value: 'claude-opus-4-20250514' },
  { title: 'Claude Haiku 4.5 (fastest)',    value: 'claude-haiku-4-5-20251001' },
];

export async function runConfigWizard() {
  console.log('Claude ZeroClaw — Configuration Wizard\n');
  console.log('This will create or update your .env file.\n');

  const answers = await prompts([
    {
      type: 'text',
      name: 'host',
      message: 'Bind host',
      initial: '0.0.0.0',
    },
    {
      type: 'number',
      name: 'port',
      message: 'Port',
      initial: 8080,
    },
    {
      type: 'select',
      name: 'default_model',
      message: 'Default Claude model',
      choices: MODELS,
    },
    {
      type: 'number',
      name: 'max_turns',
      message: 'Max conversation turns',
      initial: 10,
    },
    {
      type: 'number',
      name: 'cli_timeout',
      message: 'Claude CLI timeout (seconds)',
      initial: 300,
    },
    {
      type: 'text',
      name: 'api_key',
      message: 'Optional gateway API key (leave blank for no auth)',
      initial: '',
    },
    {
      type: 'toggle',
      name: 'debug',
      message: 'Enable debug logging',
      initial: false,
      active: 'yes',
      inactive: 'no',
    },
  ]);

  const envLines = [
    '# Claude ZeroClaw — generated by config wizard',
    `CZG_HOST=${answers.host}`,
    `CZG_PORT=${answers.port}`,
    `CZG_DEFAULT_MODEL=${answers.default_model}`,
    `CZG_MAX_TURNS=${answers.max_turns}`,
    `CZG_CLI_TIMEOUT=${answers.cli_timeout}`,
    answers.api_key ? `CZG_API_KEY=${answers.api_key}` : '# CZG_API_KEY=',
    `CZG_DEBUG=${answers.debug}`,
    '# CZG_WORKING_DIR=',
    '# CZG_CLAUDE_BIN=claude',
  ];

  const envPath = path.resolve(process.cwd(), '.env');
  fs.writeFileSync(envPath, envLines.join('\n') + '\n');

  console.log(`\n✅ Config written to ${envPath}`);
  console.log(`   Start the gateway: ./claude-zeroclaw`);
}
